stages:
  - ansible_gather_facts
  - ansible_final_deployment

variables:
  ANSIBLE_SSH_PRIVATE_KEY: ${CI_PROJECT_DIR}/project1.pem
  DOCKER_CLI_TIMEOUT: 1200

# ansible_gather_facts:
#   image: alpine
#   tags:
#     - shell-1
#   stage: ansible_gather_facts
#   script:
#     - terraform init
#     - ansible --version
#     - ansible-playbook -i inventory.ini playbook-1.yml

ansible_final_deployment:
  image: alpine
  tags:
    - shell-1
  stage: ansible_final_deployment
  before_script:
    # - docker login -u anupamdutta -p glpat-stJHKDbwDiyT9P2_9Prz code.techverito.com:4567
    - docker login -u anupam.dutta753 -p $GITLAB_TOKEN registry.gitlab.com
  script:
    - chmod 400 project1.pem
    - ansible-playbook -i inventory.ini --private-key=project1.pem --user ubuntu --extra-vars="ansible_ssh_common_args='-o StrictHostKeyChecking=no'" playbook-2.yml



