name: Ansible Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [trigger-ansible]

jobs:
  ansible_final_deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        
    - name: Set TAG variable
      run: echo "TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV

    - name: Print TAG variable
      run: echo "TAG is $TAG"

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
       ssh-private-key: ${{ secrets.PRIVATE_KEY }}
       log-public-key: false
    
    - name: Run Ansible playbook
      run: ansible-playbook -i inventory.ini --user ubuntu --extra-vars="ansible_ssh_common_args='-o StrictHostKeyChecking=no' TAG=$TAG" playbook-2.yml
      env:
       TAG: $TAG
    # - name: Run Ansible playbook for final deployment
    #   run: |
    #    ansible-playbook -i inventory.ini --private-key <(echo "$ANSIBLE_SSH_PRIVATE_KEY") --user ubuntu --extra-vars="ansible_ssh_common_args='-o StrictHostKeyChecking=no'" playbook-2.yml
    #    env:
    #    ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
