name: Ansible Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [trigger-ansible]
env:
 TAG: ${{ github.event.client_payload.image_tag }}
 
jobs:

  scanning:
    name: GitGuardian scan and Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: GitGuardian scan
        uses: GitGuardian/ggshield-action@v1.24.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GGS_TOKEN }}
    
      
  ansible_final_deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
     
        
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
       ssh-private-key: ${{ secrets.PRIVATE_KEY }}
       log-public-key: false
    - name: Set TAG variable
      run: echo "TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV

    - name: Print TAG variable
      run: echo "TAG is $TAG"

    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: ".env"
        target: "$HOME/"
      
    - name: Start Docker containers
      run: |
       export TAG="testing"
       ansible-playbook -i inventory.ini --user ubuntu --extra-vars="ansible_ssh_common_args='-o StrictHostKeyChecking=no'" playbook-2.yml
